version: '2'

services:
    couchbase:
        image: couchbase
        ports:
            - 8091:8091
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
 
    tescotills-order:
        image: tescotills-order
        ports:
            - 8080:8080
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
        restart: always